### ISSUE TITLE
Treinamento básico de git

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-Grupo9#1]

**Comment by FilipeKN4** [comment]
Treinamento realizado no dia 18/08

**Comment by micheldcamargo** [comment]
Material disponível no repositório da disciplina: https://github.com/fga-eps-mds/A-Disciplina/wiki/Git

**Comment by Mikhaelle** [comment]
Curso grátis de Git na Udemy:https://www.udemy.com/git-e-github-para-iniciantes/
